global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'substations'
    static_configs:
      - targets: ['substation1:8000', 'substation2:8000', 'substation3:8000']
  
  - job_name: 'load_balancer'
    static_configs:
      - targets: ['load_balancer:8000']