version: "3"
services:
  node1:
    build: .
    ports:
      - "5001:5000"
    command: ["python", "node.py", "node1", "node1,node2,node3"]

  node2:
    build: .
    ports:
      - "5002:5000"
    command: ["python", "node.py", "node2", "node1,node2,node3"]

  node3:
    build: .
    ports:
      - "5003:5000"
    command: ["python", "node.py", "node3", "node1,node2,node3"]
